name: Povarenok CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  backend-unit-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'corretto'
          cache: maven

      - name: Backend unit tests
        run: mvn test -Dtest=ru/spbstu/povarenok/*/*
        working-directory: ./Backend
        
  frontend-unit-tests:
    
    needs: backend-unit-tests

    runs-on: ubuntu-latest

    steps:

      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Frontend unit tests
        run: |
          npm ci
          npm test
        working-directory: ./Frontend

  backend-integration-tests:

    needs: frontend-unit-tests

    runs-on: ubuntu-latest

    steps:

      - name: Get repository code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
          cache: maven

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./Frontend/package-lock.json

      - name: Backend integration tests
        run: mvn test -Dtest="integration/*"
        working-directory: ./Backend

  

